apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nb-agents 
  description: A Python microservice on the NB platform   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used tssc-gitops as the grouping
    acs/deployment-name: nb-agents
    acs.secured-by: "production"
    argocd/app-selector: tssc/gitops=nb-agents
    backstage.io/kubernetes-id: nb-agents 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: nb-agents
    quay.io/repository-slug: tssc/nb-agents
  tags: ["python", "pip", "flask", "sscs", "sbom", "acs", "nb-coe"] 
spec:
  type: service
  owner: group:default/tssc 
  lifecycle: experimental
 
